# Generated by Django 5.2.8 on 2025-11-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('date_posted', models.DateField()),
                ('read_time', models.CharField(default='5 min read', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('image_url', models.URLField(default='https://placehold.co/800x600')),
                ('icon_name', models.CharField(default='award', help_text='lucide icon name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technologies', models.CharField(help_text='Comma separated, e.g. Django, React', max_length=200)),
                ('image_url', models.URLField(default='https://placehold.co/600x400/png')),
                ('github_link', models.URLField(blank=True)),
                ('live_link', models.URLField(blank=True)),
                ('full_content', models.TextField(help_text='HTML or Markdown for the detail view')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
