# Generated by Django 5.2.8 on 2025-11-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='feature_image',
            field=models.ImageField(blank=True, default='blog_images/default.jpg', upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(help_text='You can use Markdown here (e.g., **bold**, # Heading)'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='read_time',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='certification',
            name='icon_name',
            field=models.CharField(default='award', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_content',
            field=models.TextField(help_text='Markdown/HTML supported'),
        ),
    ]
