# Generated by Django 5.2.8 on 2025-11-21 21:54

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blog_feature_image_alter_blog_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='You can use Markdown here (e.g., **bold**, # Heading)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_content',
            field=markdownx.models.MarkdownxField(help_text='Markdown/HTML supported'),
        ),
    ]
