# Generated by Django 5.2.8 on 2025-11-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_blog_content_alter_project_full_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.ImageField(blank=True, default='project_images/default.jpg', upload_to='project_images/'),
        ),
    ]
