# Generated by Django 5.2.8 on 2025-11-22 09:46

import django.utils.timezone
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('content', markdownx.models.MarkdownxField()),
                ('feature_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_time', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
