# Generated by Django 5.2.8 on 2025-11-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_article_slug_project_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='issuer',
            new_name='issuing_organization',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certificate_image',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='icon_name',
        ),
        migrations.AddField(
            model_name='article',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='credential_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='certification',
            name='credential_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
