# Generated by Django 5.2.8 on 2025-11-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_article_views_project_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['-issue_date']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='certification',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
