# Generated by Django 5.2.8 on 2025-11-27 00:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_certification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
