# Generated by Django 5.2.8 on 2026-01-02 18:48

import django_ckeditor_5.fields as ckeditor_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=ckeditor_fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='content',
            field=ckeditor_fields.CKEditor5Field(help_text='Markdown/HTML supported'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='summary',
            field=ckeditor_fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='certification',
            name='description',
            field=ckeditor_fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor_fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_content',
            field=ckeditor_fields.CKEditor5Field(help_text='Markdown/HTML supported'),
        ),
    ]
