# Generated by Django 5.2.8 on 2026-01-02 19:24

import django_ckeditor_5.fields as ckeditor5_fields
import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_article_content_alter_article_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='technologies',
            field=models.CharField(blank=True, default='', help_text='Comma separated, e.g. Python, SQL', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor5_fields.CKEditor5Field(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=ckeditor5_fields.CKEditor5Field(verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='content',
            field=ckeditor5_fields.CKEditor5Field(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='summary',
            field=ckeditor5_fields.CKEditor5Field(verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='description',
            field=ckeditor5_fields.CKEditor5Field(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor5_fields.CKEditor5Field(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_content',
            field=ckeditor5_fields.CKEditor5Field(verbose_name='Content'),
        ),
        migrations.CreateModel(
            name='CaseStudyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.casestudy')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
