# Generated by Django 6.0 on 2026-01-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_casestudy_technologies_alter_article_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
